env:
  browser: true
  node: true
  greasemonkey: true
  es2020: true
  jquery: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  entryPoint: false
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  max-len: ['error', { code: 120 }]
  no-console: off
  no-continue: off
  prefer-rest-params: off
  no-underscore-dangle: off
  no-param-reassign: off
  no-plusplus: off
  no-control-regex: off
  no-await-in-loop: off
  no-restricted-syntax: ["error", "ForInStatement", "LabeledStatement", "WithStatement"]

